#!/usr/bin/env ruby

require 'erb'

# Usage:
#   gen-pack some-template.erb 1
#   gen-pack some-template.erb 5
#
erb_path      = ARGV[0]
num_instances = ARGV[1].to_i
pkg_url       = ARGV[2] || 'http://packages.couchbase.com/releases/1.7.0/membase-server-community_x86_1.7.0.rpm'

print ERB.new(IO.read(erb_path)).result(binding)
print "\n"
